# Generated by Django 5.2.6 on 2025-10-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_rooms_alter_listing_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='descritpion',
            new_name='description',
        ),
    ]
