# Generated by Django 5.2.6 on 2025-10-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_descritpion_listing_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='screens',
        ),
        migrations.AddField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('Private Rooms', 'Private Rooms'), ('Semi-Private Rooms', 'Semi-Private Rooms'), ('Standard (Multi-bed) Rooms', 'Standard (Multi-bed) Rooms')], default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='professionals',
        ),
        migrations.AddField(
            model_name='listing',
            name='professionals',
            field=models.ManyToManyField(blank=True, to='listings.subject'),
        ),
    ]
