# Generated by Django 5.2.6 on 2025-10-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_subject_remove_listing_screens_listing_room_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_publish',
            new_name='is_published',
        ),
    ]
